import type { Metadata } from "next";
import { Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import {ConvexClientProvider} from "@/components/ConvexClientProvider";
import React from "react";
import {ConvexAuthNextjsServerProvider} from "@convex-dev/auth/nextjs/server"
import {Modals} from "@/components/modals";
import {Toaster} from "@/components/ui/sonner";
import {JotaiProvider} from "@/components/jotai-provider";
import { cn } from "@/lib/utils";

const geist = Geist({subsets:['latin'],variable:'--font-sans'});

const geistMono = Geist_Mono({
  variable: "--font-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ConvexAuthNextjsServerProvider>
        <html lang="en" className={cn("antialiased", geistMono.variable, "font-sans", geist.variable)}>
        <body>
        <ConvexClientProvider>

            <JotaiProvider>

                <Modals/>
                <Toaster />
                {children}

            </JotaiProvider>


        </ConvexClientProvider>
        </body>
        </html>
    </ConvexAuthNextjsServerProvider>
  );
}
